# Generated by Django 5.2.1 on 2025-05-29 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Omonimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'omonimlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OmonimTafsiloti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelib_chiqishi', models.CharField(max_length=100)),
                ('etimologiyasi', models.TextField()),
                ('soz_turkum', models.CharField(max_length=25)),
                ('lugaviy_manosi', models.TextField()),
                ('misol', models.TextField()),
                ('omonim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omonimlar.omonimlar')),
            ],
            options={
                'db_table': 'omonimlar_tafsiloti',
                'ordering': ['omonim'],
            },
        ),
    ]
